---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  # url: https://kubernetes-sigs.github.io/external-dns/
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      # version: "1.12.0" # k8s-sigs
      version: "6.13.2" # bitnami
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
    # sources: "service\ningress\n"
    # sidecars: []
  values:
    # --source=source ...
    # The resource types that are queried for
    # endpoints; specify multiple times for multiple
    #  node, fake, connector, gateway-httproute,
    #  gateway-grpcroute, gateway-tlsroute,
    #  gateway-tcproute, gateway-udproute,
    #  istio-gateway, istio-virtualservice,
    # cloudfoundry, contour-ingressroute,
    #  contour-httpproxy, gloo-proxy, crd, empty,
    #  skipper-routegroup, openshift-route,
    # ambassador-host, kong-tcpingress)
    # ####
    # --default-targets=DEFAULT-TARGETS ...
    # Set globally default IP address that will apply as a target instead of source addresses.
    # Specify multiple times for multiple targets
    sources:
      - service
      - ingress
      - crd
    triggerLoopOnEvent: true
    crd:
      create: true
      kind: "DNSEndpoint"
      version: "externaldns.k8s.io/v1alpha1"
    # txtPrefix: ii
    provider: pdns
    # clusterDomain: cluster.local
    pdns:
      apiUrl: http://auth.powerdns.svc.cluster.local
      apiPort: 8081
      apiKey: hackbach
      # secretName:
# ---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: localhost-ii-nz
#   namespace: external-dns
# spec:
#   endpoints:
#     - dnsName: localhost.ii.nz
#       recordTTL: 1
#       recordType: A
#       targets:
#         - 127.0.0.1
# https://github.com/sharingio/pair/blob/ba677970f9fb2c83c4cddcf63c347f8b0977569b/org/explorations/external-dns-powerdns/external-dns.yaml#L88
# Some interesting VRS
# Pair soa
# https://github.com/sharingio/pair/blob/74c8c9e92db14d3bd3912513c28c6e3bb3b68151/.sharing.io/pair-soa.yaml
