# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: powerdns
#   labels:
#     toolkit.fluxcd.io/tenant: sre-team
---
# https://github.com/aescanero/helm-charts
# https://github.com/pschiffe/docker-pdns
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: powerdns
  namespace: powerdns
spec:
  interval: 24h
  type: oci
  url: oci://reg.hackbach.nz/charts/powerdns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: powerdns
  namespace: powerdns
spec:
  interval: 30m
  chart:
    spec:
      chart: powerdns
      version: "0.1.11"
      sourceRef:
        kind: HelmRepository
        name: powerdns
        namespace: powerdns
      interval: 12h
  values:
    installCRDs: true
