---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
# https://github.com/aescanero/helm-charts
# https://github.com/pschiffe/docker-pdns
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 24h
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: powerdns
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 12h
  values:
    hostname: harbor.hackbach.nz
    http:
      port: 80
    https:
      port: 443
      # certificate:
      # private_key:
    internal_tls:
      enabled: true
      dir: X?
