apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   path: ./clusters/thinkpad
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
resources:
  - ./infra.yaml
  - ./gitops.yaml
  - ../../infrastructure/loadbalancer/metallb/metallb.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-ns.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-admin.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-auth.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-admin-configmap.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-postgres.yaml
  - ../../infrastructure/ingress/nginx/nginx-ingress.yaml
  - ../../infrastructure/certs/cert-manager/cert-manager.yaml
  - ../../infrastructure/storage/rook/rook-ceph.yaml
  # Apps
  - ../../apps/ii.nz/ii.nz.yaml
  - ../../apps/ii.nz/matey.ii.nz.yaml
  - ../../apps/careers.cloudnative.nz/deployment.yaml
  - ../../apps/ghost/ghost.yaml
  - ../../apps/coder/coder.yaml
  - ../../apps/coder/coder-ingress.yaml
  - ../../apps/coder/cluster-admin-role.yaml
  - ../../apps/coder/coder-helmrelease.yaml
  - ../../apps/multiplex/deployment.yaml
  # - ../../apps/minecraft/itzg-minecraft.yaml
  # - ../../apps/ii.nz/localhost.ii.nz.yaml
  # FOR LATER
  # - ../../infrastructure/dns/powerdns/external-dns.yaml
  # Tryingto get PowerDNS into a chart?
  # - ../../infrastructure/dns/powerdns/ii-powerdns.yaml
  # We don't use dist YET
  # - ../../infrastructure/dns/powerdns/manifests/powerdns-dnsdist.yaml
  # we don't use recursor YET
  # - ../../infrastructure/dns/powerdns/manifests/powerdns-recursor.yaml
  # Infra Config
  # To remove, need to run this first:
  # kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag
  # https://github.com/longhorn/longhorn/blob/69dcfa527784c0ccd80830cf0fd1852ac888ef04/chart/README.md#uninstallation
  # - ../../infrastructure/storage/longhorn/longhorn.yaml
  # - ../../infrastructure/storage/longhorn/longhorn-ingress.yaml
  # Infra that needs CRDs
  #- ./metallb-config.yaml
spec:
  patches:
    # How GHOST_ENABLE_HTTPS is used by the container
    # From https://github.com/bitnami/containers/blob/main/bitnami/ghost/5/debian-11/rootfs/opt/bitnami/scripts/libghost.sh#L437-L444
    # if is_boolean_yes "$GHOST_ENABLE_HTTPS"; then
    #    scheme="https"
    #    [[ "$GHOST_EXTERNAL_HTTPS_PORT_NUMBER" != "443" ]] && host+=":${GHOST_EXTERNAL_HTTPS_PORT_NUMBER}"
    # fi
    # echo "${scheme}://${host}"
    # Also GHOST_ENABLE_HTTPS must be yes or no
    # ghost argument from https://github.com/bitnami/containers/blob/main/bitnami/ghost/5/debian-11/rootfs/opt/bitnami/scripts/libghost.sh#L290-L300
    #                 "--url" "$base_url"
    # NOTE: this is only performed once, and call ghost_configure_host()
    # From https://github.com/bitnami/containers/blob/main/bitnami/ghost/5/debian-11/rootfs/opt/bitnami/scripts/libghost.sh#L456-L463
    # ghost_conf_set "url" "$base_url"
    # Fix an existing deployment via:
    # kubectl -n ghost exec deployment/ghost -- cat /bitnami/ghost/config.production.json
    # kubectl -n ghost exec deployment/ghost -- sed -i s/http:/https:/ /bitnami/ghost/config.production.json
    - target:
        kind: Deployment
        name: ghost
        namespace: ghost
      patch: |
        - path: /spec/containers/0/env
          op: add
          value:
            name: "GHOST_ENABLE_HTTPS"
            value: "yes"
        # - path: /spec/containers/0/env
        #   op: add
        #   value:
        #     name: "GHOST_ENABLE_HTTPS"
        #     value: "yes"
