---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-stable
  namespace: nginx
spec:
  interval: 24h
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx-ingress
      version: "0.16.1"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: nginx
      interval: 12h
  values:
    controller:
      wildcardTLS:
        # The base64-encoded TLS certificate for every Ingress/VirtualServer host that has TLS enabled but no secret specified. If the parameter is not set, for such Ingress/VirtualServer hosts NGINX will break any attempt to establish a TLS connection.
        # cert: ""
        # The base64-encoded TLS key for every Ingress/VirtualServer host that has TLS enabled but no secret specified. If the parameter is not set, for such Ingress/VirtualServer hosts NGINX will break any attempt to establish a TLS connection.
        # key: ""
        secret: nginx/ii.nz-tls
        # The secret with a TLS certificate and key for every Ingress/VirtualServer host that has TLS enabled but no secret specified. The value must follow the following format: <namespace>/<name>. Used as an alternative to specifying a certificate and key using controller.wildcardTLS.cert and controller.wildcardTLS.key parameters.
