---
apiVersion: v1
kind: Namespace
metadata:
  name: ii-nz
  labels:
    environment: production
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ii-nz
  namespace: ii-nz
  labels:
    environment: production
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: ii-nz-letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "ii.nz"
  rules:
    - host: "ii.nz"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ii-nz
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ii-nz
  namespace: ii-nz
  labels:
    environment: production
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ii-nz-website
