---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: localhost-ii-nz
  namespace: external-dns
spec:
  endpoints:
    - dnsName: localhost.ii.nz
      recordTTL: 1
      recordType: A
      targets:
        - 127.0.0.1
    - dnsName: "localhost2.ii.nz"
      recordTTL: 1
      recordType: A
      targets:
        - 127.0.0.1
    # - dnsName: "*.localhost.ii.nz"
    #   recordTTL: 1
    #   recordType: A
    #   targets:
    #     - 127.0.0.1
