---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matey-ii-nz
  namespace: coder
  labels:
    environment: production
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: ii-nz-letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "matey.ii.nz"
  rules:
    - host: "matey.ii.nz"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: matey-ii-nz
                port:
                  number: 81
---
apiVersion: v1
kind: Service
metadata:
  name: matey-ii-nz
  namespace: coder
  labels:
    environment: production
spec:
  ports:
    - port: 81
      targetPort: 81
  selector:
    name: coder-hh-ii-nz
