---
apiVersion: v1
kind: Namespace
metadata:
  name: phone-ii-nz
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phone-ii-nz
  namespace: phone-ii-nz
  labels:
    environment: production
  annotations:
    cert-manager.io/cluster-issuer: ii-nz-letsencrypt-prod
    # kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "phone.ii.nz"
  rules:
    - host: "phone.ii.nz"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: phone-ii-nz
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: phone-ii-nz
  namespace: phone-ii-nz
  labels:
    environment: production
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: phone-ii-nz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-ii-nz
  namespace: phone-ii-nz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phone-ii-nz
  template:
    metadata:
      labels:
        app: phone-ii-nz
    spec:
      automountServiceAccountToken: false
      containers:
        - name: phone-ii-nz
          image: ghcr.io/ii/phone-webinstall:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Pacific/Auckland"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          # securityContext:
          #   readOnlyRootFilesystem: true
          #   runAsUser: 1000
          #   runAsGroup: 1000
          #   allowPrivilegeEscalation: false
          # resources:
          #   requests:
          #     memory: "60Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "60Mi"
          #     cpu: "500m"
