---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: default
automountServiceAccountToken: true
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: hello-world
  namespace: default
spec:
  path: ./infrastructure/terraform/hello-world
  interval: 10m
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
