---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: default
automountServiceAccountToken: true
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: hello-world
  namespace: default
spec:
  path: ./
  interval: 10m
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: infra-terraform-hello-world
    namespace: flux-system
