---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: hello-world
  namespace: flux-system
spec:
  path: ./
  interval: 10m
  approvePlan: auto
  storeReadablePlan: json
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
