---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: wildcard-ii-nz
  namespace: external-dns
spec:
  endpoints:
    - dnsName: "ii.nz"
      recordTTL: 1
      recordType: A
      targets:
        - 103.233.62.77
    # TXT records are created with * to track
    # Would need to disable TXT registry tracking
    # - dnsName: "*.ii.nz"
    #   recordTTL: 1
    #   recordType: A
    #   targets:
    #     - 103.233.62.77
