apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   path: ./clusters/thinkpad
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
resources:
  - ../../infrastructure/loadbalancer/metallb/metallb.yaml
  - ../../infrastructure/ingress/nginx/nginx-ingress.yaml
  # - ../../infrastructure/certs/cert-manager/cert-manager.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-ns.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-admin.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-auth.yaml
  # - ../../infrastructure/dns/powerdns/external-dns.yaml
  - ./infra.yaml
  # Tryingto get PowerDNS into a chart?
  # - ../../infrastructure/dns/powerdns/ii-powerdns.yaml
  # We don't use dist YET
  # - ../../infrastructure/dns/powerdns/manifests/powerdns-dnsdist.yaml
  # we don't use recursor YET
  # - ../../infrastructure/dns/powerdns/manifests/powerdns-recursor.yaml
  # Infra Config
  # To remove, need to run this first:
  # kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag
  # https://github.com/longhorn/longhorn/blob/69dcfa527784c0ccd80830cf0fd1852ac888ef04/chart/README.md#uninstallation
  # - ../../infrastructure/storage/longhorn/longhorn.yaml
  # - ../../infrastructure/storage/longhorn/longhorn-ingress.yaml
  # Infra that needs CRDs
  #- ./metallb-config.yaml
  # Apps
  # - ../../apps/minecraft/itzg-minecraft.yaml
  # - ../../apps/ii.nz/ii.nz.yaml
  # - ../../infrastructure/certs/cert-manager/ii-nz.yaml
  # - ../../apps/coder/coder.yaml
  # - ../../apps/ii.nz/localhost.ii.nz.yaml
