---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.longhorn.io
---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  suspend: false
  # releaseName: "longhorn-longhorn" # Defaults to a composition of '[TargetNamespace-]Name'.
  # targetNamespace: "longhorn" # Defaults to the namespace of the HelmRelease.
  # storageNamespace: "" # Defaults to the namespace of the HelmRelease.
  # DependsOn: [] # a dependency.CrossNamespaceDependencyReference slice with
  #                references to HelmRelease resources
  #                that must be ready before this HelmRelease can be reconciled.
  targetNamespace: "longhorn-system" # Defaults to the namespace of the HelmRelease.
  chart:
    install:
      createNamespace: true
    upgrade:
      crds: CreateReplace
    interval: 12h
    spec:
      chart: longhorn
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
