---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: powerdns
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
# https://artifacthub.io/packages/helm/bitnami/postgresql
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pdns-db
  namespace: powerdns
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "12.5.7" # Current as of June 15, 2023
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: powerdns
      interval: 12h
  values:
    auth:
      existingSecret: powerdns
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: postgres-password
    persistence:
      size: 10Gi
