apiVersion: v1
data:
  pdns-poststart.py: |
    #!/usr/bin/env python3
    import os

    from powerdnsadmin import create_app
    from powerdnsadmin.models.base import db
    from powerdnsadmin.models.user import User, Role
    from powerdnsadmin.models.domain import Domain
    from powerdnsadmin.models.setting import Setting

    app = create_app()
    ctx = app.app_context()
    ctx.push()

    db.session.add(Setting("pdns_api_key", os.environ["SECRET_KEY"]))
    db.session.add(Setting("allow_user_create_domain", True))
    db.session.add(Setting("otp_field_enabled", False))
    db.session.add(Setting("session_timeout", 60))
    db.session.add(Setting("site_name", os.environ["PDNS_SITE_NAME"]))
    db.session.add(Setting("pdns_api_url", os.environ["PDNS_URL"]))
    db.session.add(Setting("pdns_version", os.environ["PDNS_VERSION"]))

    admin_user = os.environ["PDNS_ADMIN_USER"]
    admin_pass = os.environ["PDNS_ADMIN_PASSWORD"]
    admin_email = os.environ["PDNS_ADMIN_EMAIL"]
    admin_user = User(
        username=admin_user,
        plain_text_password=admin_pass,
        email=admin_email,
        role_id=Role.query.filter_by(name="Administrator").first().id,
    )
    admin_user.create_local_user()
    db.session.commit()

    # Decided configuration for zones is better left with auth
    # DNS Admin just needs admin users created
    # for declared_domain in os.environ["PDNS_DOMAINS"].split(" "):
    #     db.session.add(Domain(name=declared_domain))
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: powerdns-admin
  namespace: powerdns
