apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infra that needs CRDs
  - ./metallb-config.yaml
  # Apps
  - ../../../apps/ii.nz/localhost.ii.nz.yaml
  - ../../../infrastructure/certs/cert-manager/ii-nz.yaml
  - ../../../apps/ii.nz/ii.nz.yaml
  # - ../../../apps/minecraft/itzg-minecraft.yaml
  # - ../../../apps/coder/coder.yaml
