---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  # url: https://kubernetes-sigs.github.io/external-dns/
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      # version: "1.12.0" # k8s-sigs
      version: "6.13.2" # bitnami
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    sources:
      - service
      - ingress
    crd:
      create: true
    txtPrefix: ii
    provider: pdns
    clusterDomain: hackbach.cluster
    pdns:
      apiUrl: http://auth.default.svc.hackbach.cluster
      apiPort: 8081
      apiKey: hackbach
      # secretName:
# ---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: localhost-ii-nz
#   namespace: external-dns
# spec:
#   endpoints:
#     - dnsName: localhost.ii.nz
#       recordTTL: 1
#       recordType: A
#       targets:
#         - 127.0.0.1
