---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "20.8.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    ingressRoute:
      dashboard:
        enabled: true
        labels: {}
        annotations:
          kubernetes.io/ingress.class: cilium
    # providers:
    #   kubernetesCRD:
    #     enabled: true
    #   kubernetesIngress:
    #     enabled: true
    logs:
      general:
        level: DEBUG
        # level: ERROR
      access:
        level: DEBUG
        # level: ERROR
    # providers:
    #   publishedService:
    #     enable: false
    #     # ^ could this be true?
    hostNetwork: false
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.1.145
        # clusterIP: 192.168.1.145
      externalIPs:
        - 103.233.62.77
      ipFamilies:
        - IPv4
      # loadBalancerRanges:
      #   - 192.168.1.156/32
    image:
      name: traefik
      # tag: v2.9.6
