apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infra that has IPS
  # - ./authentik.yaml
  - ./metallb-config.yaml
  - ./powerdns-ingress.yaml
  - ./careers.cloudnative.nz.yaml
  - ./multiplex.ii.nz.yaml
  # Certs
  - ./certs/cloudnative-nz.yaml
  # - ./ii.nz-dns.yaml
  # - ./coder.ii.nz-ingress.yaml
  # Infra that needs CRDs
  # Apps
  # - ../../../apps/ii.nz/localhost.ii.nz.yaml
  # - ../../../infrastructure/certs/cert-manager/ii-nz.yaml
  # - ../../../apps/ii.nz/ii.nz.yaml
  # - ../../../apps/minecraft/itzg-minecraft.yaml
  # - ../../../apps/coder/coder.yaml
  # - ../../../apps/phone.ii.nz/phone.ii.nz.yaml
