# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-cloudnative-nz
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: dns@ii.coop
#     privateKeySecretRef:
#       name: letsencrypt-cloudnative-nz
#     solvers:
#       - dns01:
#           rfc2136:
#             tsigKeyName: ii
#             tsigAlgorithm: HMACMD5
#             tsigSecretSecretRef:
#               name: tsig-powerdns
#               key: powerdns
#             nameserver: 123.253.176.253
#             # nameserver: 103.233.62.77 # 139.178.68.188
#         selector:
#           dnsNames:
#             - "*.cloudnative.nz"
#             - "cloudnative.nz"
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: letsencrypt-cloudnative-nz
#   namespace: cert-manager
# spec:
#   secretName: letsencrypt-cloudnative-nz
#   issuerRef:
#     name: letsencrypt-cloudnative-nz
#     kind: ClusterIssuer
#   commonName: "*.cloudnative.nz"
#   dnsNames:
#     - cloudnative.nz
#     - "*.cloudnative.nz"
