apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/minecraft/itzg-minecraft.yaml
  - ../../infrastructure/loadbalancer/metallb/metallb.yaml
  - ../../infrastructure/ingress/nginx/nginx-ingress.yaml
  - ../../infrastructure/storage/longhorn/longhorn.yaml
  - ../../infrastructure/certs/cert-manager/certmanager.yaml
  # Tryingto get PowerDNS into a chart?
  # - ../../infrastructure/dns/powerdns/ii-powerdns.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-admin.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-auth.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-dnsdist.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-recursor.yaml
