apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   path: ./clusters/thinkpad
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
resources:
  - ../../infrastructure/loadbalancer/metallb/metallb.yaml
  - ../../infrastructure/ingress/nginx/nginx-ingress.yaml
  # - ../../infrastructure/storage/longhorn/longhorn.yaml
  - ../../infrastructure/certs/cert-manager/cert-manager.yaml
  - ../../infrastructure/dns/powerdns/external-dns.yaml
  # Tryingto get PowerDNS into a chart?
  # - ../../infrastructure/dns/powerdns/ii-powerdns.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-ns.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-admin.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-auth.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-dnsdist.yaml
  - ../../infrastructure/dns/powerdns/manifests/powerdns-recursor.yaml
  # Infra Config
  # - ../../infrastructure/storage/longhorn/longhorn-ingress.yaml
  - ./metallb-config.yaml
  # Apps
  - ../../apps/minecraft/itzg-minecraft.yaml
  - ../../apps/ii.nz/ii.nz.yaml
  - ../../infrastructure/certs/cert-manager/ii-nz.yaml
  # - ../../apps/coder/coder.yaml
  # - ../../apps/ii.nz/localhost.ii.nz.yaml
