---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: coder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: coder
    name: cluster-admin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
