---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: coder
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder-db
  namespace: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "12.1.14"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: coder
      interval: 12h
  values:
    auth:
      username: coder
      password: coder
      database: coder
    persistence:
      size: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  namespace: nginx
type: Opaque
data:
  url: cG9zdGdyZXM6Ly9jb2Rlcjpjb2RlckBjb2Rlci1kYi1wb3N0Z3Jlc3FsLmNvZGVyLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvY29kZXI/c3NsbW9kZT1kaXNhYmxl
