---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: itzg
  namespace: minecraft
spec:
  interval: 24h
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: minecraft
      interval: 12h
  values:
    minecraftServer:
      eula: true
      gameMode: survival
      motd: "Welcome to Ashers server!"
      worldSaveName: "AshLand"
      serviceType: LoadBalancer
      rcon:
        enable: true
        serviceType: LoadBalancer
