---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-fop-nz
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dns@ii.coop
    privateKeySecretRef:
      name: letsencrypt-fop-nz
    solvers:
      - dns01:
          rfc2136:
            tsigKeyName: ii
            tsigAlgorithm: HMACMD5
            tsigSecretSecretRef:
              name: tsig-powerdns
              key: powerdns
            nameserver: 123.253.176.253
            # nameserver: 103.233.62.77 # 139.178.68.188
        selector:
          dnsNames:
            - "*.fop.nz"
            - "fop.nz"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-fop-nz
  namespace: cert-manager
spec:
  secretName: letsencrypt-fop-nz
  issuerRef:
    name: letsencrypt-fop-nz
    kind: ClusterIssuer
  commonName: "*.fop.nz"
  dnsNames:
    - fop.nz
    - "*.fop.nz"
