---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-sharing-io
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dns@ii.coop
    privateKeySecretRef:
      name: letsencrypt-sharing-io
    solvers:
      - dns01:
          rfc2136:
            tsigKeyName: ii
            tsigAlgorithm: HMACMD5
            tsigSecretSecretRef:
              name: tsig-powerdns
              key: powerdns
            nameserver: 123.253.176.253
            # nameserver: 103.233.62.77 # 139.178.68.188
        selector:
          dnsNames:
            - "*.sharing.io"
            - "sharing.io"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-sharing-io
  namespace: cert-manager
spec:
  secretName: letsencrypt-sharing-io
  issuerRef:
    name: letsencrypt-sharing-io
    kind: ClusterIssuer
  commonName: "*.sharing.io"
  dnsNames:
    - sharing.io
    - "*.sharing.io"
