---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-workshop-coop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dns@ii.coop
    privateKeySecretRef:
      name: letsencrypt-workshop-coop
    solvers:
      - dns01:
          rfc2136:
            tsigKeyName: ii
            tsigAlgorithm: HMACMD5
            tsigSecretSecretRef:
              name: tsig-powerdns
              key: powerdns
            nameserver: 123.253.176.253
            # nameserver: 103.233.62.77 # 139.178.68.188
        selector:
          dnsNames:
            - "*.workshop.coop"
            - "workshop.coop"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-workshop-coop
  namespace: cert-manager
spec:
  secretName: letsencrypt-workshop-coop
  issuerRef:
    name: letsencrypt-workshop-coop
    kind: ClusterIssuer
  commonName: "*.workshop.coop"
  dnsNames:
    - workshop.coop
    - "*.workshop.coop"
